version: '3.3'  # version of compose format

services:
  landing-service:
    build: ./landing  # path is relative to docker-compose.yml location
    hostname: landing-service
    ports:
      - 5050:5050  # host:container
    networks:
      sample:
        aliases:
          - landing-service
   # Add more services below
  addition-service:
    build: ./addition
    hostname: addition-service
    ports:
      - 5051:5050
    networks:
      sample:
        aliases:
          - addition-service

  subtraction-service:
    build: ./subtraction
    hostname: subtraction-service
    ports:
      - 5052:5050
    networks:
      sample:
        aliases:
          - subtraction-service

  multiplication-service:
    build: ./multiplication
    hostname: multiplication-service
    ports:
      - 5053:5050
    networks:
      sample:
        aliases:
          - multiplication-service

  division-service:
    build: ./division
    hostname: division-service
    ports:
      - 5054:5050
    networks:
      sample:
        aliases:
          - division-service

  gcd-service:
    build: ./gcd
    hostname: gcd-service
    ports:
      - 5055:5050
    networks:
      sample:
        aliases:
          - gcd-service

  lcm-service:
    build: ./lcm
    hostname: lcm-service
    ports:
      - 5056:5050
    networks:
      sample:
        aliases:
          - lcm-service

  exponent-service:
    build: ./exponent
    hostname: exponent-service
    ports:
      - 5057:5050
    networks:
      sample:
        aliases:
          - exponent-service
  


networks:
  sample: